name: Rust
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          default: true
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-rust_stable-${{ hashFiles('**/Cargo.toml') }}
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update -qqy
          sudo apt-get install -qqy libudev-dev
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rust-docs
          default: true
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-rust_nightly-${{ hashFiles('**/Cargo.toml') }}
      - name: Documentation
        uses: actions-rs/cargo@v1
        env:
          DOCS_RS: 1
        with:
          command: doc

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update -qqy
          sudo apt-get install -qqy libudev-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: clippy
          default: true
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-rust_nightly-${{ hashFiles('**/Cargo.toml') }}
      - name: Build cache
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-build-rust_nightly-check-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-features

  check-minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true
          override: true
      - name: Install libudev
        run: |
          sudo apt-get update -qqy
          sudo apt-get install -qqy libudev-dev
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-rust_nightly-${{ hashFiles('**/Cargo.toml') }}
      - name: Build cache
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-build-rust_nightly-check-minimal-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --all-features -Z minimal-versions

  test:
    needs:
      - format
      - doc
      - check
      - check-minimal
    strategy:
      fail-fast: ${{ startsWith(github.ref, 'refs/tags/') }}
      matrix:
        include:
          # Generate bindings
          - task: bindings
            os: ubuntu-latest
            rust: stable
            target: i686-unknown-linux-gnu
          - task: bindings
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
          - task: bindings
            os: ubuntu-latest
            rust: stable
            target: arm-unknown-linux-gnueabihf
          - task: bindings
            os: ubuntu-latest
            rust: stable
            target: armv7-unknown-linux-gnueabihf
          - task: bindings
            os: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-gnu
          # Test channels
          - task: channels
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
          - task: channels
            os: ubuntu-latest
            rust: beta
            target: x86_64-unknown-linux-gnu
          - task: channels
            os: ubuntu-latest
            rust: nightly
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    container: ubuntu:focal
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: |
          TZ=Etc/UTC
          ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime
          echo ${TZ} > /etc/timezone
          apt-get update -qqy
          apt-get install -qqy sudo curl gcc pkg-config libclang-dev dpkg-dev
      - name: Setup linux toolchain
        if: contains(matrix.target, '-linux-') && startsWith(matrix.target, 'x86_64-')
        run: |
          sudo apt-get install -y libinput-dev libudev-dev
      - name: Setup cross linux toolchain
        if: contains(matrix.target, '-linux-') && !startsWith(matrix.target, 'x86_64-')
        run: |
          GCC_TARGET=$(printf "${{ matrix.target }}" | sed 's/-unknown-/-/;s/arm[^-]*/arm/;s/riscv[^-]*/riscv64/')
          ENV_TARGET=$(printf "${{ matrix.target }}" | tr '-' '_'  | tr '[[:lower:]]' '[[:upper:]]')
          sudo apt-get update -y
          sudo apt-get install -y gcc-${GCC_TARGET}
          echo "CARGO_TARGET_${ENV_TARGET}_LINKER=${GCC_TARGET}-gcc" >> $GITHUB_ENV
          echo "BINDGEN_EXTRA_CLANG_ARGS=--sysroot=/usr/${GCC_TARGET} -isystem ${PWD}/.github/workflows/cross-include" >> $GITHUB_ENV
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          profile: minimal
          components: rustfmt
          default: true
          override: true
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-rust_${{ matrix.rust }}-${{ hashFiles('**/Cargo.toml') }}
      - name: Build cache
        if: |
          runner.os != 'macOS'
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-build-rust_${{ matrix.rust }}-target_${{ matrix.target }}-${{ hashFiles('**/Cargo.toml') }}
      - name: Update deps
        uses: actions-rs/cargo@v1
        with:
          command: update
      - name: Build sys
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: bindgen=warn,bindgen::ir=error,bindgen::codegen=error
        with:
          command: build
          args: --manifest-path input-sys/Cargo.toml --target ${{ matrix.target }} --no-default-features --features update_bindings,libinput_1_11,libinput_1_14,libinput_1_15,libinput_1_19,libinput_1_21
      - name: Copy bindings
        run: |
          for i in input-sys/src/bindings/*.rs
          do
              cp $i $(basename $i .rs)-${{ matrix.target }}.rs
          done
      - name: Upload bindings
        if: matrix.task == 'bindings'
        uses: actions/upload-artifact@v3
        with:
          name: bindings
          path: gen_*.rs
      - name: Build
        if: contains(matrix.target, '-linux-') && startsWith(matrix.target, 'x86_64-')
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}
      - name: Build
        if: contains(matrix.target, '-linux-') && !startsWith(matrix.target, 'x86_64-')
        uses: actions-rs/cargo@v1
        with:
          command: build
          # Disable udev feature so we don't need library in cross-sysroot
          args: --target ${{ matrix.target }} --no-default-features --features log,libinput_1_21
      - name: Test
        if: contains(matrix.target, '-linux-') && startsWith(matrix.target, 'x86_64-')
        uses: actions-rs/cargo@v1
        timeout-minutes: 12
        env:
          RUST_BACKTRACE: full
        with:
          command: test
          args: --all --target ${{ matrix.target }}

  compare-bindings:
    needs:
      - test
    runs-on: ubuntu-22.04
    steps:
      - name: download bindings
        uses: actions/download-artifact@v3
        with:
          name: bindings
      - name: compare
        run: |
          code=0
          for i in gen_*.rs
          do
            base=$(echo ${i} | cut -f 1 -d -)
            if cmp -s ${base}-x86_64-unknown-linux-gnu.rs ${i}
            then
              echo ${i} matches x86_64 bindings
            else
              echo ${i} does not match x86_64 bindings
              diff ${base}-x86_64-unknown-linux-gnu.rs ${i}
              code=1
            fi
          done
          exit ${code}

  # TODO copy x86
  update-bindings:
    if: ${{ github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/tags/') }}
    needs:
      - compare-bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download bindings
        uses: actions/download-artifact@v3
        with:
          name: bindings
      - name: Copy x86_64 bindings
        run: |
          for i in gen_*-x86_64-unknown-linux-gnu.rs
          do
              cp $i input-sys/src/bindings/$(basename i x86_64-unknown-linux-gnu.rs).rs
          done
          rm gen_*.rs
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          base: ${{ github.head_ref }}
          commit-message: Updated bindings
          branch: update-bindings
          delete-branch: true
          title: Update bindings
          body: |
            Bindings should be updated to be consistent with latest changes

  publish:
    if: github.repository == 'Smithay/input.rs' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - format
      - doc
      - check
      - check-minimal
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Publish crates
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATES_TOKEN }}
          args: --no-verify
          #dry-run: true
